### ISSUE TITLE
Chapter title not identified when using a unique sharp

### ISSUE THREAD

**Issue by taophp** [lise-henry/crowbook#1]
When you use only on sharp to define the chapter title, it is not recognized by Crowbook.

The markdown specifications said that:
```
#My Title
```
is equivalent to:
```
My Title
========
```
but Crowbook does not treat them the same way... and simply do not see any title when using the sharp version.

**Comment by lise-henry** [comment]
It's actually the behaviour of [pulldown-cmark](https://github.com/google/pulldown-cmark), which Crowbook uses internally. It follows the [CommonMark](http://spec.commonmark.org/0.23/#atx-headings) specification, which says that there must be a space after # to consider it a title. Unless Crowbook use its own Markdown parser there's not much I can do on this, sorry ^^

**Comment by taophp** [comment]
Oh, I wasn't aware of this required space. Thank you for pointing it.
