### ISSUE TITLE
TOC of guide.book is inconsistent in html/epub 

### ISSUE THREAD

**Issue by stefan0xC** [lise-henry/crowbook#100]
TOC entries with children will have their HTML tags escaped (e.g. instead of `2.10 <code> --to</code>` it will be `2.10 &lt;code&gt--to&lt/code&gt;`) while others (e.g. `2.9. <code>--verbose</code>`) are unchanged.

I think the inconsistency was already fixed upstream (see lise-henry/epub-builder#25) but there has not been a release of a new version. (Also I'm not sure if we really want HTML tags escaped in the TOC.)

Downgrading the `epub-builder` crate from "0.5" to "0.4" fixes this behavior.

**Comment by stefan0xC** [comment]
Since the 0.16.0 version uses a newer version of the crate all TOC entries with HTML will be escaped. But there is still the following difference between [PDF](https://github.com/lise-henry/crowbook/blob/master/docs/book/book.pdf) (left) and [EPUB](https://github.com/lise-henry/crowbook/blob/master/docs/book/book.epub)/[HTML](https://github.com/lise-henry/crowbook/blob/master/docs/book/book.html):
![crowbook-toc-inconsistency](https://github.com/lise-henry/crowbook/assets/509385/d8fdeeed-91e9-4ac8-a003-1dcac02a92bc)

**Comment by lise-henry** [comment]
Why can’t things work nicely 😿 Thanks,  I’ll have to look into this
