### ISSUE TITLE
Error rendering pdf

### ISSUE THREAD

**Issue by sphinxc0re** [lise-henry/crowbook#35]
When rendering my book, I get the following output:
```
Info: Succesfully generated EPUB: working_9_to_FOSS.epub
Error: Error rendering pdf: Error during temporary files editing: could not open file in tmp directory: 'result.pdf'
```
After that I find an EPUB and a PDF file in my working directory but the PDF file is empty.

I'm on maxOS Sierra.

**Comment by lise-henry** [comment]
It's probably some LaTeX error (or if LaTeX isn't installed). To get a more useful error message, you can generate a .tex file and try running `xelatex` on it (a working installation of latex is unfortunately required). I'll have to fix the error message to make it clearer, though.

**Comment by lilianmoraru** [comment]
To solve "LaTeX isnt' installed", maybe this could be switched to [Tectonic](https://tectonic-typesetting.github.io/en-US/index.html) / https://docs.rs/tectonic/0.1.6/tectonic/ ?
