### ISSUE TITLE
Error when running epubcheck on rendered ePub

### ISSUE THREAD

**Issue by jasikpark** [lise-henry/crowbook#41]
When I try to open the rendered ePub in iBooks, it rejects it because:

` Line 116: attributes construct error`
`Line 116: Couldn't find end of Start Tag reference`

and when I run the same book through epubcheck, I get this:

`Validating using EPUB version 2.0.1 rules.
FATAL(RSC-016): deathworlders.epub/OEBPS/content.opf(116,50): Fatal Error while parsing file 'Element type "reference" must be followed by either attribute specifications, ">" or "/>".'.
ERROR(RSC-005): deathworlders.epub/OEBPS/content.opf(-1,-1): Error while parsing file 'Element type "reference" must be followed by either attribute specifications, ">" or "/>".'.
ERROR(OPF-031): deathworlders.epub/OEBPS/content.opf(114,72): File listed in reference element in guide was not declared in OPF manifest: OEBPS/nav.xhtml.
ERROR(OPF-031): deathworlders.epub/OEBPS/content.opf(115,80): File listed in reference element in guide was not declared in OPF manifest: OEBPS/title_page.xhtml.
ERROR(RSC-008): deathworlders.epub/OEBPS/content.opf(114,72): Referenced resource is not declared in the OPF manifest.
ERROR(RSC-008): deathworlders.epub/OEBPS/content.opf(115,80): Referenced resource is not declared in the OPF manifest.
WARNING(OPF-003): deathworlders.epub/deathworlders.epub(-1,-1): Item 'OEBPS/chapter_000.xhtml' exists in the EPUB, but is not declared in the OPF manifest.
WARNING(OPF-003): deathworlders.epub/deathworlders.epub(-1,-1): Item 'OEBPS/chapter_001.xhtml' exists in the EPUB, but is not declared in the OPF manifest.
WARNING(OPF-003): deathworlders.epub/deathworlders.epub(-1,-1): Item 'OEBPS/chapter_002.xhtml' exists in the EPUB, but is not declared in the OPF manifest.
WARNING(OPF-003): deathworlders.epub/deathworlders.epub(-1,-1): Item 'OEBPS/chapter_003.xhtml' exists in the EPUB, but is not declared in the OPF manifest.
WARNING(OPF-003): deathworlders.epub/deathworlders.epub(-1,-1): Item 'OEBPS/chapter_004.xhtml' exists in the EPUB, but is not declared in the OPF manifest.
WARNING(OPF-003): deathworlders.epub/deathworlders.epub(-1,-1): Item 'OEBPS/chapter_005.xhtml' exists in the EPUB, but is not declared in the OPF manifest.
WARNING(OPF-003): deathworlders.epub/deathworlders.epub(-1,-1): Item 'OEBPS/chapter_006.xhtml' exists in the EPUB, but is not declared in the OPF manifest.
WARNING(OPF-003): deathworlders.epub/deathworlders.epub(-1,-1): Item 'OEBPS/chapter_007.xhtml' exists in the EPUB, but is not declared in the OPF manifest.
WARNING(OPF-003): deathworlders.epub/deathworlders.epub(-1,-1): Item 'OEBPS/chapter_008.xhtml' exists in the EPUB, but is not declared in the OPF manifest.
WARNING(OPF-003): deathworlders.epub/deathworlders.epub(-1,-1): Item 'OEBPS/chapter_009.xhtml' exists in the EPUB, but is not declared in the OPF manifest.
WARNING(OPF-003): deathworlders.epub/deathworlders.epub(-1,-1): Item 'OEBPS/chapter_010.xhtml' exists in the EPUB, but is not declared in the OPF manifest.
WARNING(OPF-003): deathworlders.epub/deathworlders.epub(-1,-1): Item 'OEBPS/chapter_011.xhtml' exists in the EPUB, but is not declared in the OPF manifest.
WARNING(OPF-003): deathworlders.epub/deathworlders.epub(-1,-1): Item 'OEBPS/chapter_012.xhtml' exists in the EPUB, but is not declared in the OPF manifest.
WARNING(OPF-003): deathworlders.epub/deathworlders.epub(-1,-1): Item 'OEBPS/chapter_013.xhtml' exists in the EPUB, but is not declared in the OPF manifest.
WARNING(OPF-003): deathworlders.epub/deathworlders.epub(-1,-1): Item 'OEBPS/chapter_014.xhtml' exists in the EPUB, but is not declared in the OPF manifest.
WARNING(OPF-003): deathworlders.epub/deathworlders.epub(-1,-1): Item 'OEBPS/chapter_015.xhtml' exists in the EPUB, but is not declared in the OPF manifest.
WARNING(OPF-003): deathworlders.epub/deathworlders.epub(-1,-1): Item 'OEBPS/chapter_016.xhtml' exists in the EPUB, but is not declared in the OPF manifest.
WARNING(OPF-003): deathworlders.epub/deathworlders.epub(-1,-1): Item 'OEBPS/chapter_017.xhtml' exists in the EPUB, but is not declared in the OPF manifest.
WARNING(OPF-003): deathworlders.epub/deathworlders.epub(-1,-1): Item 'OEBPS/chapter_018.xhtml' exists in the EPUB, but is not declared in the OPF manifest.
WARNING(OPF-003): deathworlders.epub/deathworlders.epub(-1,-1): Item 'OEBPS/chapter_019.xhtml' exists in the EPUB, but is not declared in the OPF manifest.
WARNING(OPF-003): deathworlders.epub/deathworlders.epub(-1,-1): Item 'OEBPS/chapter_020.xhtml' exists in the EPUB, but is not declared in the OPF manifest.
WARNING(OPF-003): deathworlders.epub/deathworlders.epub(-1,-1): Item 'OEBPS/chapter_021.xhtml' exists in the EPUB, but is not declared in the OPF manifest.
WARNING(OPF-003): deathworlders.epub/deathworlders.epub(-1,-1): Item 'OEBPS/chapter_022.xhtml' exists in the EPUB, but is not declared in the OPF manifest.
WARNING(OPF-003): deathworlders.epub/deathworlders.epub(-1,-1): Item 'OEBPS/chapter_023.xhtml' exists in the EPUB, but is not declared in the OPF manifest.
WARNING(OPF-003): deathworlders.epub/deathworlders.epub(-1,-1): Item 'OEBPS/chapter_024.xhtml' exists in the EPUB, but is not declared in the OPF manifest.
WARNING(OPF-003): deathworlders.epub/deathworlders.epub(-1,-1): Item 'OEBPS/chapter_025.xhtml' exists in the EPUB, but is not declared in the OPF manifest.
WARNING(OPF-003): deathworlders.epub/deathworlders.epub(-1,-1): Item 'OEBPS/chapter_026.xhtml' exists in the EPUB, but is not declared in the OPF manifest.
WARNING(OPF-003): deathworlders.epub/deathworlders.epub(-1,-1): Item 'OEBPS/chapter_027.xhtml' exists in the EPUB, but is not declared in the OPF manifest.
WARNING(OPF-003): deathworlders.epub/deathworlders.epub(-1,-1): Item 'OEBPS/chapter_028.xhtml' exists in the EPUB, but is not declared in the OPF manifest.
WARNING(OPF-003): deathworlders.epub/deathworlders.epub(-1,-1): Item 'OEBPS/chapter_029.xhtml' exists in the EPUB, but is not declared in the OPF manifest.
WARNING(OPF-003): deathworlders.epub/deathworlders.epub(-1,-1): Item 'OEBPS/chapter_030.xhtml' exists in the EPUB, but is not declared in the OPF manifest.
WARNING(OPF-003): deathworlders.epub/deathworlders.epub(-1,-1): Item 'OEBPS/chapter_031.xhtml' exists in the EPUB, but is not declared in the OPF manifest.
WARNING(OPF-003): deathworlders.epub/deathworlders.epub(-1,-1): Item 'OEBPS/chapter_032.xhtml' exists in the EPUB, but is not declared in the OPF manifest.
WARNING(OPF-003): deathworlders.epub/deathworlders.epub(-1,-1): Item 'OEBPS/chapter_033.xhtml' exists in the EPUB, but is not declared in the OPF manifest.
WARNING(OPF-003): deathworlders.epub/deathworlders.epub(-1,-1): Item 'OEBPS/chapter_034.xhtml' exists in the EPUB, but is not declared in the OPF manifest.
WARNING(OPF-003): deathworlders.epub/deathworlders.epub(-1,-1): Item 'OEBPS/chapter_035.xhtml' exists in the EPUB, but is not declared in the OPF manifest.
WARNING(OPF-003): deathworlders.epub/deathworlders.epub(-1,-1): Item 'OEBPS/chapter_036.xhtml' exists in the EPUB, but is not declared in the OPF manifest.
WARNING(OPF-003): deathworlders.epub/deathworlders.epub(-1,-1): Item 'OEBPS/chapter_037.xhtml' exists in the EPUB, but is not declared in the OPF manifest.
WARNING(OPF-003): deathworlders.epub/deathworlders.epub(-1,-1): Item 'OEBPS/chapter_038.xhtml' exists in the EPUB, but is not declared in the OPF manifest.
WARNING(OPF-003): deathworlders.epub/deathworlders.epub(-1,-1): Item 'OEBPS/chapter_039.xhtml' exists in the EPUB, but is not declared in the OPF manifest.
WARNING(OPF-003): deathworlders.epub/deathworlders.epub(-1,-1): Item 'OEBPS/chapter_040.xhtml' exists in the EPUB, but is not declared in the OPF manifest.
WARNING(OPF-003): deathworlders.epub/deathworlders.epub(-1,-1): Item 'OEBPS/chapter_041.xhtml' exists in the EPUB, but is not declared in the OPF manifest.
WARNING(OPF-003): deathworlders.epub/deathworlders.epub(-1,-1): Item 'OEBPS/chapter_042.xhtml' exists in the EPUB, but is not declared in the OPF manifest.
WARNING(OPF-003): deathworlders.epub/deathworlders.epub(-1,-1): Item 'OEBPS/chapter_043.xhtml' exists in the EPUB, but is not declared in the OPF manifest.
WARNING(OPF-003): deathworlders.epub/deathworlders.epub(-1,-1): Item 'OEBPS/chapter_044.xhtml' exists in the EPUB, but is not declared in the OPF manifest.
WARNING(OPF-003): deathworlders.epub/deathworlders.epub(-1,-1): Item 'OEBPS/nav.xhtml' exists in the EPUB, but is not declared in the OPF manifest.
WARNING(OPF-003): deathworlders.epub/deathworlders.epub(-1,-1): Item 'OEBPS/stylesheet.css' exists in the EPUB, but is not declared in the OPF manifest.
WARNING(OPF-003): deathworlders.epub/deathworlders.epub(-1,-1): Item 'OEBPS/title_page.xhtml' exists in the EPUB, but is not declared in the OPF manifest.
WARNING(OPF-003): deathworlders.epub/deathworlders.epub(-1,-1): Item 'OEBPS/toc.ncx' exists in the EPUB, but is not declared in the OPF manifest.`

**Comment by jasikpark** [comment]
<img width="1440" alt="screenshot 2017-09-26 14 44 37" src="https://user-images.githubusercontent.com/10626596/30880767-47b89b64-a2c9-11e7-9fb6-61dccf4b7a7d.png">

it seems to be complaining because of the fact that I have apostrophes contained in the title of one of my chapter titles. That's messing up the reference in content.opf.

**Comment by jasikpark** [comment]
IT WAS THE APOSTROPHES!!!! meh. Thanks for rubber-ducking though. I just deleted the apostrophes from the chapter title, and it worked. I believe that is still a bug in `crowbook` though.

**Comment by lise-henry** [comment]
Thanks for reporting that! Indeed, quotes should be escaped, looking into this.
