### ISSUE TITLE
Error when creating single markdown page

### ISSUE THREAD

**Issue by JekoTronik** [lise-henry/crowbook#54]
I just download the v0.14 .deb file for 64bits system and dpkg -i on it.
Then I tried to create a single markdown page and all I got is this error :
```
$ crowbook --lang en -s text.md
CROWBOOK 0.14.0
X text.md: Could not find file 'text.md' for book chapter
ERROR text.md: Could not find file 'text.md' for book chapter
```

**Comment by lise-henry** [comment]
Does the file "text.md" exist? I get this error when it doesn't exist.
