### ISSUE TITLE
Drop ODT output?

### ISSUE THREAD

**Issue by lise-henry** [lise-henry/crowbook#61]
Not really an issue, but more a lot of issues with the ODT output, which has totally fallen behind and I am not able to maintain. I am thinking of dropping it for the time being, particularly since copy/pasting HTML output into LibreOffice probably gives some better result. But am open to some feedback, is anybody actually using this feature?

**Comment by hirschenberger** [comment]
No

**Comment by jrappen** [comment]
No

**Comment by stefan0xC** [comment]
I would propose to make the (experimental) odt output optional by turning it into an [feature](https://doc.rust-lang.org/cargo/reference/features.html). If the code hidden by the feature interferes with your work you can still drop it later?
