### ISSUE TITLE
Code syntax highlighting breaks after comments

### ISSUE THREAD

**Issue by jrappen** [lise-henry/crowbook#65]
Code syntax highlighting breaks for me after comments. This is reproducible with other languages.

Using the latest binary from the releases for mac, `crowbook-v0.14.0-x86_64-apple-darwin`.

---

<img width="634" alt="image" src="https://user-images.githubusercontent.com/8577450/70457369-53294000-1ab0-11ea-8024-cf4aa04cbefb.png">

**Comment by lise-henry** [comment]
I can't reproduce in later version, it's possible moving to a newer version of syntect fixed the issue.

**Comment by jrappen** [comment]
If you have the time, could you publish binaries on the releases page?

**Comment by lise-henry** [comment]
Unfortunately, it's not a matter of time, but that I am unable to fix the Travis and Appveyor configuration that allowed to build binaries for other targets than linux/amd64. I'll try to look at other solutions but I can't guarantee anything :s

**Comment by jrappen** [comment]
GitHub actions might be an option:

* https://github.com/actions/starter-workflows/blob/master/ci/rust.yml
* https://github.com/actions/create-release
* https://github.com/actions/upload-release-asset

**Comment by jrappen** [comment]
@lise-henry I built the mac binary locally. Is indeed fixed with `v0.15.0`. Closing this issue now.
