### ISSUE TITLE
Builds binaries for targets other than Linux/x86

### ISSUE THREAD

**Issue by lise-henry** [lise-henry/crowbook#67]
Currently, I am unable to build binaries for other targets than Linux. In the past, I used trust to build and deploy binaries using Travis and Appveyor but I have been unable/incompetent to do it for the past few releases.

So if someone understands these platforms better than me (that's not hard ^^) and has any idea how to fix the appveyor.yml/.travis.yml files and/or what I need to do on these sites I'd be more than happy :)

Logs on travis (it doesn't even build there anymore because of syntect?) : https://travis-ci.org/lise-henry/crowbook
Logs on appveyor: https://ci.appveyor.com/project/lise-henry/crowbook (here it builds correctly but i am incapable of deploying: https://ci.appveyor.com/project/lise-henry/crowbook/deployment/2575742)

**Comment by jrappen** [comment]
Using GitHub workflows might be an option. Haven't read through all of this to be able to present a solution at the moment.

However I'll post some links for reference in the meantime.

---

## Help articles

* https://help.github.com/articles/about-github-actions
* https://help.github.com/articles/automating-your-workflow-with-github-actions
* https://help.github.com/articles/configuring-a-workflow

## Relevant workflow examples

* https://github.com/actions/starter-workflows/blob/master/ci/rust.yml
* https://github.com/actions/create-release
* https://github.com/actions/download-artifact
* https://github.com/actions/upload-release-asset

**Comment by jrappen** [comment]
To fix the `Travis.ci` and `AppVeyor` scripts, having a look at <https://github.com/tree-sitter/tree-sitter> might help.

I'm not too familiar with either, though. So this is just a guess.

**Comment by jrappen** [comment]
@lise-henry I could drop a binary for x64 mac of `crowbook v0.15.0` if that helps, while this issue remains unresolved.

**Comment by lise-henry** [comment]
It has finally been solved for the 0.15.2 release. Feel free to comment for other builds and I'll see what I can do, as long as it's still working :)
