### ISSUE TITLE
X pdf: Error during temporary files editing: xelatex didn't return succesfully

### ISSUE THREAD

**Issue by jacometoss** [lise-henry/crowbook#85]
ERROR Error rendering pdf: Error during temporary files editing: xelatex didn't return succesfully
miktex 21.3

Run the CrowBook ​​Archives test
Install current Miktex but cannot generate PDF on Windows 10 Operating System

choco install miktext

**Comment by jacometoss** [comment]
if you have TextMaker installed this causes the error you must uninstall it if you want to use Crowbook

**Comment by hustcer** [comment]
I got the same error: `❌ pdf: Error during temporary files editing: xelatex didn't return succesfully` on my mac, and I can not figure out why, so sad
