### ISSUE TITLE
Is this project dead? :/

### ISSUE THREAD

**Issue by hoijui** [lise-henry/crowbook#87]
Would it be possible, to give the maximum rights to some of the people that contributed to this project so far?
Looking at the pull-requests, I see there are some candidates; maybe @hirschenberger and @jrappen?
I would add at least 2, better more. In any case, it is unlikely they will do something really bad, and it can't be much worse then a dead projects, which is what this looks like now.

**Comment by jrappen** [comment]
I mainly added docs and fixed a few typos. I'm not a Rust guy.

**Comment by jrappen** [comment]
@hoijui If you have anything to add to this, just open a pull request? I found Élisabeth to be quite responsive.

**Comment by hoijui** [comment]
@jrappen I see an open pull request from November 2020 (which can be accepted without discussion, so obviously useful and harmful it is), and the last commit was in September 2020. Together with you saying, that you found her to be responsive, i must conclude, that for some reason, she gave up on this project. That's totally fine - live happens, but it would be nice to allow it to live on anyway, by giving others rights.

**Comment by lise-henry** [comment]
Dead I don't know, but quite comatose at the time that's for sure :D
I indeed totally forgot about this PR. 
I am open to give rights to other people if there is some interest in it but I don't think I got a lot of contributions that are really meaningful to the Rust code and I think it's probably on this front that a new maintainer would be most helpful (e.g. to make actual new releases that really work on other platforms than linux, update the code base to newer versions of Rust and so on).

**Comment by hoijui** [comment]
oh.. answering on the same day on a weekend.. yeah.. not dead indeed!
.. all good then!
let's see if someone can be found here for things you mentioned! :-)
(I don't have time, and am not using the project myself)

**Comment by hirschenberger** [comment]
Hi, sorry for the delayed answer. 
I contributed some stuff to crowbook, mainly to fix my own papercuts while using it and as a nice opportunity for procrastination.
I really like that software and hope it will survive, at least being maintained on a basic level. For me it is feature-complete and works well for what I use(-ed) it for.
I'd be open to help porting it to the current edition and do some minor maintanace tasks if necessary.
